name: pdfbox_dart
description: Dart port of pdfbox
version: 1.0.0
#homepage: https://github.com/insinfo/

environment:
  sdk: ^3.6.0

dependencies:
  pointycastle: ^4.0.0
  meta: ^1.3.0
  collection: ^1.14.13
  archive: ^4.0.7
  crypto: ^3.0.7
  petitparser: '>=5.1.0 <8.0.0'
  image: ^4.5.4
  http: any #^1.5.0
  logging: any
  # xml: ^6.3.0
  # xpath_selector: ^3.0.2
  # xpath_selector_xml_parser: ^3.0.1
  # ninja: ^3.0.8
  

dev_dependencies:
  # lints: ^5.1.1
  # melos: ^6.3.2
  test: any

